--- 
pool: 
  vmImage: "Ubuntu 16.04"
steps: 
  - 
    displayName: "Install Node.js"
    inputs: 
      versionSpec: 8.x
    task: NodeTool@0
  - 
    inputs: 
      secureFile: environment.ts
    task: DownloadSecureFile@1
  - 
    inputs: 
      secureFile: environment.prod.ts
    task: DownloadSecureFile@2
  - 
    inputs: 
      Contents: |
          environment.ts
          environemts.prod.ts
      TargetFolder: $(Build.SourcesDirectory)/src/environments
      sourceFolder: $(Agent.TempDirectory)
    task: CopyFiles@2
  - 
    displayName: "npm install and build"
    script: |
        npm install
        npm run build-prod
