# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'
  
- task: DownloadSecureFile@1
  inputs:
    secureFile: environment.ts
    
- task: DownloadSecureFile@1
  inputs:
    secureFile: environment.prod.ts

- task: CopyFiles@2
  inputs:
    sourceFolder: $(Agent.TempDirectory)
    Contents: |
      environment.ts
      environment.prod.ts
    TargetFolder: '$(Build.SourcesDirectory)/src/environments'

- script: |
    npm install
    npm run build-prod
  displayName: 'npm install and build'
 
- task: SSH@0
  inputs:
    sshEndpoint: sydney1
    runOptions: commands
    commands: cd /usr/share/nginx/www/michaelrausch.nz/ ; rm -f *.bundle.js
  
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: sydney1
    sourceFolder: dist/
    targetFolder: /usr/share/nginx/www/michaelrausch.nz/
  
